cite 'about-alias'
about-alias 'personal custom aliases'

# Common command
alias ls='ls --color'
alias lsa='ls --all --color'
alias ll='ls -l'
alias lla='ls -l --all --color'
alias la='ls -la'
alias v='vim'
alias vi='vim'
alias sv='sudo vim'

# Grep command
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Common setting for Git
alias gf='git fetch'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gmg='git merge'
alias grv='git remote -v'
alias gbr='git branch'
alias gst='git status'
alias ga='git add'
alias grm='git rm'
alias gcm='git commit'
alias grb='git rebase -i'
alias gpl='git pull'
alias gps='git push'
alias gdf='git diff'
alias gsh='git show'
alias gshs='git show --stat'
alias gsts='git stash'
alias gstp='git stash pop'
alias grs='git reset'
alias gcl='git clean'
alias glo='git log --oneline --color=auto'
alias glog='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
